import { useState, useRef, useEffect } from "react";
import { UploadCloud, ChevronDown, ChevronRight, Printer, CheckCircle2, FileText, Sparkles, Zap, Menu, X, MessageSquare, Plus, RotateCcw, Download } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";
import DocumentGenerationPanel from "../components/DocumentGenerationPanel";

const GENERATE_ENDPOINT = "/generate";
const MAX_UPLOAD_SIZE_BYTES = 100 * 1024 * 1024;


function showToast(message) {
  if (window.Toastify) {
    window.Toastify({
      text: message,
      duration: 4000,
      gravity: "top",
      position: "right",
      stopOnFocus: true,
      close: true,
      style: {
        background: "linear-gradient(135deg, #0f172a, #1e3a8a)",
        color: "#ffffff",
        borderRadius: "12px",
        boxShadow: "0 10px 30px rgba(15, 23, 42, 0.25)",
      },
    }).showToast();
    return;
  }

  window.alert(message);
}

function getDuration(totalMarks) {
  if (totalMarks <= 25) return "45 Mins";
  if (totalMarks <= 50) return "1.5 Hours";
  return "3 Hours";
}

const GRADES = ["Nursery", "Grade SrKg", "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", "Under Graduate", "Post Graduate"];
const BOARDS = ["CBSE", "ICSE", "State Board", "IB", "IGCSE", "Cambridge", "Other"];
const DIFFICULTIES = ["Easy", "Medium", "Hard", "Advanced"];

const defaultForm = {
  subject: "Physics",
  grade: "",
  board: "",
  difficulty: "",
  totalMarks: 50,
  prompt: "",
  sections: [
    { id: 'A', type: "Objective Analysis", marks: 1, count: 10, enabled: true },
    { id: 'B', type: "Conceptual Synthesis", marks: 3, count: 5, enabled: true },
    { id: 'C', type: "Comprehensive Argumentation", marks: 5, count: 3, enabled: true }
  ]
};

const pageVariants = {
  initial: (direction) => ({ opacity: 0, x: direction > 0 ? 30 : -30 }),
  animate: { opacity: 1, x: 0, transition: { duration: 0.4, ease: [0.22, 1, 0.36, 1] } },
  exit: (direction) => ({ opacity: 0, x: direction > 0 ? -30 : 30, transition: { duration: 0.3, ease: [0.4, 0, 1, 1] } }),
};

function sanitizeFilenamePart(value) {
  return String(value || "")
    .trim()
    .replace(/\s+/g, "_")
    .replace(/[^A-Za-z0-9_-]/g, "")
    .replace(/^_+|_+$/g, "");
}

function buildExpectedFilename({ subject, grade, board, marks }) {
  const parts = [
    sanitizeFilenamePart(subject),
    sanitizeFilenamePart(grade),
    sanitizeFilenamePart(board),
    sanitizeFilenamePart(marks ? `${marks}_Marks` : ""),
  ].filter(Boolean);

  return `${parts.join("_") || "Generated_Question_Paper"}.docx`;
}

function looksAutoGeneratedFilename(filename) {
  const normalized = String(filename || "").trim();
  return /^[a-f0-9]{24,}\.docx$/i.test(normalized);
}

function validatePrompt(prompt, subject, hasFiles) {
  const rawPrompt = (prompt || "").trim();
  const combined = `${subject || ""} ${rawPrompt}`.trim().toLowerCase();

  if (!rawPrompt && !hasFiles) {
    return "Please enter a clear academic prompt before generating.";
  }

  const unsafePattern = /\b(sex|sexual|porn|nude|adult|escort|fetish|kill|murder|bomb|weapon|terror|attack|suicide|self[- ]?harm|hack|hacking|phish|phishing|malware|ransomware|drugs?|cocaine|heroin|meth|fraud|scam|forgery|counterfeit|hate|abuse|harass|harassment|girlfriend|boyfriend|dating|flirt|romance)\b/i;
  if (unsafePattern.test(rawPrompt)) {
    return "This prompt is outside safe academic question paper generation. Please enter a valid academic prompt.";
  }

  const unrelatedPattern = /\b(hello|hi|hey|how are you|who are you|what are you|joke|story|poem|lyrics|song|roast|meme|recipe|cook|food|weather|news|movie|instagram|love advice|relationship|chatgpt|openai|gemini)\b/i;
  const academicPattern = /\b(question\s*paper|exam|test|quiz|worksheet|assignment|assessment|chapter|unit|lesson|topic|syllabus|curriculum|mcq|multiple\s*choice|short\s*answer|long\s*answer|numerical|derivation|physics|chemistry|biology|science|mathematics|math|algebra|geometry|history|geography|english|grammar|literature|computer|programming|economics|accountancy|commerce|civics|political\s*science)\b/i;
  const paperStructurePattern = /\b(q\d+[a-z]?|question\s*\d+|main\s*question|sub\s*question|section|part|marks?|format|pattern|q1|q2|q3|q4|q5|q6|q7|q8|q9|q10)\b/i;
  const hasAcademicContext = academicPattern.test(combined) || paperStructurePattern.test(rawPrompt);

  if (unrelatedPattern.test(rawPrompt) && !hasAcademicContext) {
    return "This prompt is not related to academic question paper generation. Please enter a valid academic prompt.";
  }

  if (!hasAcademicContext && !hasFiles) {
    return "Please enter an academic prompt related to a subject, topic, chapter, exam, or question paper.";
  }

  return "";
}

function getPreviewBlocks(previewText) {
  return String(previewText || "")
    .split(/\n\s*\n/)
    .map((block) => block.split("\n").map((line) => line.trim()).filter(Boolean))
    .filter((block) => block.length > 0);
}

function PreviewPaper({ paper, previewText }) {
  if (!paper || (!paper.title && !paper.sections?.length)) {
    return (
      <div className="space-y-6">
        {getPreviewBlocks(previewText).map((block, index) => {
          const firstLine = block[0] || "";
          const restLines = block.slice(1);
          const isMainTitle = index === 0;
          const isSectionHeading = /^section\b/i.test(firstLine) || /^[A-Z][A-Za-z0-9\s]+$/.test(firstLine);
          const isMetaRow = firstLine.includes("Subject:") || firstLine.includes("Total Marks:");

          if (isMainTitle) {
            return (
              <div key={`preview-block-${index}`} className="text-center">
                <h2 className="text-3xl font-bold text-slate-900" style={{ fontFamily: '"Playfair Display", serif' }}>
                  {firstLine}
                </h2>
                {restLines.map((line, lineIndex) => (
                  <p key={`preview-line-${index}-${lineIndex}`} className="mt-2 text-sm font-medium text-slate-500">
                    {line}
                  </p>
                ))}
              </div>
            );
          }

          if (isMetaRow) {
            return (
              <div key={`preview-block-${index}`} className="flex flex-wrap gap-x-6 gap-y-2 border-b border-slate-200 pb-4 text-sm font-medium text-slate-600">
                {firstLine.split("|").map((item, itemIndex) => (
                  <span key={`meta-${index}-${itemIndex}`}>{item.trim()}</span>
                ))}
              </div>
            );
          }

          if (isSectionHeading) {
            return (
              <div key={`preview-block-${index}`} className="space-y-3 pt-3">
                <h3 className="text-lg font-bold text-slate-900">{firstLine}</h3>
                {restLines.map((line, lineIndex) => (
                  <p
                    key={`preview-line-${index}-${lineIndex}`}
                    className={line.startsWith("- ") ? "pl-4 text-sm leading-7 text-slate-700" : "text-sm leading-7 text-slate-700"}
                  >
                    {line}
                  </p>
                ))}
              </div>
            );
          }

          return (
            <div key={`preview-block-${index}`} className="space-y-2">
              {block.map((line, lineIndex) => (
                <p key={`preview-line-${index}-${lineIndex}`} className="text-sm leading-7 text-slate-700">
                  {line}
                </p>
              ))}
            </div>
          );
        })}
      </div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="text-center border-b border-slate-200 pb-6">
        {paper.header && <p className="mb-2 text-base font-semibold text-slate-700">{paper.header}</p>}
        <h2 className="text-3xl font-bold text-slate-900" style={{ fontFamily: '"Playfair Display", serif' }}>
          {paper.title}
        </h2>
        <div className="mt-4 flex flex-wrap items-center justify-center gap-x-6 gap-y-2 text-sm font-medium text-slate-600">
          {paper.subject && <span>Subject: {paper.subject}</span>}
          {paper.grade && <span>Grade: {paper.grade}</span>}
          {paper.total_marks && <span>Total Marks: {paper.total_marks}</span>}
          {paper.time && <span>Duration: {paper.time}</span>}
          {paper.paper_type && <span>Paper Type: {paper.paper_type}</span>}
          {paper.difficulty && <span>Difficulty: {paper.difficulty}</span>}
        </div>
      </div>

      {paper.general_instructions?.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-lg font-bold text-slate-900">General Instructions</h3>
          <div className="space-y-2">
            {paper.general_instructions.map((instruction, index) => (
              <p key={`instruction-${index}`} className="pl-4 text-sm leading-7 text-slate-700">
                - {instruction}
              </p>
            ))}
          </div>
        </div>
      )}

      {paper.sections?.map((section, sectionIndex) => (
        <div key={`section-${sectionIndex}`} className="space-y-4 border-t border-slate-200 pt-6 first:border-t-0 first:pt-0">
          <div>
            <h3 className="text-xl font-bold text-slate-900">{section.title || `Section ${sectionIndex + 1}`}</h3>
            <div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-sm font-medium text-slate-600">
              {section.type && <span>Type: {section.type}</span>}
              {section.marks_distribution && <span>Marks: {section.marks_distribution}</span>}
            </div>
            {section.instructions && <p className="mt-2 text-sm leading-7 text-slate-700">Instructions: {section.instructions}</p>}
          </div>

          <div className="space-y-5">
            {section.questions?.map((question, questionIndex) => (
              <div key={`question-${sectionIndex}-${questionIndex}`} className="space-y-2">
                <p className="text-base font-semibold leading-7 text-slate-900">
                  {(question.question_number || questionIndex + 1)}. {question.question_text}
                </p>
                {(question.type || question.marks) && (
                  <p className="text-sm font-medium text-slate-500">
                    {[question.type, question.marks ? `Marks: ${question.marks}` : ""].filter(Boolean).join(" | ")}
                  </p>
                )}
                {question.options?.length > 0 && (
                  <div className="space-y-1 pl-5">
                    {question.options.map((option, optionIndex) => (
                      <p key={`option-${sectionIndex}-${questionIndex}-${optionIndex}`} className="text-sm leading-7 text-slate-700">
                        - {option}
                      </p>
                    ))}
                  </div>
                )}
                {question.answer && <p className="pl-5 text-sm leading-7 text-slate-700">Answer: {question.answer}</p>}
              </div>
            ))}
          </div>
        </div>
      ))}

      {paper.note && (
        <div className="border-t border-slate-200 pt-6">
          <h3 className="text-lg font-bold text-slate-900">Note</h3>
          <p className="mt-2 text-sm leading-7 text-slate-700">{paper.note}</p>
        </div>
      )}
    </div>
  );
}

export default function Dashboard({ onBack, onAbout }) {
  const [form, setForm] = useState(defaultForm);
  const [uploadedFiles, setUploadedFiles] = useState([]);
  const [filesModalOpen, setFilesModalOpen] = useState(false);
  const [filePreview, setFilePreview] = useState(null);
  const [status, setStatus] = useState("idle"); // idle, loading, variants, variant_preview, preview, generated
  const [generationError, setGenerationError] = useState("");
  const [variantPreviews, setVariantPreviews] = useState([]);
  const [previewVariant, setPreviewVariant] = useState(null);
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);
  const [output, setOutput] = useState(null);
  const [backendPrompt, setBackendPrompt] = useState(null);
  const [generatedDoc, setGeneratedDoc] = useState(null);
  const [expandedSections, setExpandedSections] = useState({ A: true, B: true, C: true });
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [activeModal, setActiveModal] = useState(null);

  const fileInputRef = useRef(null);
  const timerRef = useRef(null);
  const promptTextareaRef = useRef(null);

  const handlePreviewFile = (file) => {
     let type = '';
     if (/\.pdf$/i.test(file.name) || file.type === 'application/pdf') {
        type = 'pdf';
     } else if (/\.(jpe?g|png|gif|webp|bmp)$/i.test(file.name) || file.type.startsWith('image/')) {
        type = 'image';
     } else {
        type = 'unknown';
     }
     
     setFilePreview({
        file: file,
        name: file.name,
        type: type,
        url: URL.createObjectURL(file)
     });
  };

  const closePreview = () => {
     if (filePreview && filePreview.url) {
        URL.revokeObjectURL(filePreview.url);
     }
     setFilePreview(null);
  };

  useEffect(() => {
    return () => clearTimeout(timerRef.current);
  }, []);

  useEffect(() => {
    if (promptTextareaRef.current) {
      promptTextareaRef.current.style.height = "auto";
      promptTextareaRef.current.style.height = `${promptTextareaRef.current.scrollHeight}px`;
    }
  }, [form.prompt]);

  const handleDragOver = (e) => e.preventDefault();
  const handleDrop = (e) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      const newFiles = Array.from(e.dataTransfer.files).filter(f => {
        if (f.size > MAX_UPLOAD_SIZE_BYTES) {
           showToast(`File ${f.name} exceeds 100MB limit.`);
           return false;
        }
        return true;
      });
      if (newFiles.length > 0) {
        setUploadedFiles(prev => [...prev, ...newFiles]);
      }
    }
  };



  const handleGenerate = async () => {
    const trimmedPrompt = form.prompt.trim();
    const hasFiles = uploadedFiles.length > 0;
    const validationMessage = validatePrompt(trimmedPrompt, form.subject, hasFiles);
    if (validationMessage) {
      showToast(validationMessage);
      setGeneratedDoc(null);
      setGenerationError(validationMessage);
      setStatus("idle");
      return;
    }

    setGenerationError("");
    setStatus("loading");

    try {
      const formData = new FormData();
      formData.append("subject", form.subject);
      formData.append("grade", form.grade);
      formData.append("board", form.board);
      formData.append("difficulty", form.difficulty);
      formData.append("marks", String(form.totalMarks));
      formData.append("totalMarks", String(form.totalMarks));
      formData.append("prompt", trimmedPrompt);
      formData.append("custom_prompt", trimmedPrompt);
      formData.append("topic", trimmedPrompt || form.subject);
      formData.append("sections", JSON.stringify(form.sections));

      if (uploadedFiles.length > 0) {
        uploadedFiles.forEach(f => {
          formData.append("file", f);
        });
      }

      const response = await fetch(GENERATE_ENDPOINT, {
        method: "POST",
        body: formData
      });

      const responseText = await response.text();
      let result = null;

      if (responseText) {
        try {
          result = JSON.parse(responseText);
        } catch (parseError) {
          throw new Error(`Backend returned a non-JSON response: ${responseText.slice(0, 200)}`);
        }
      }

      if (!response.ok) {
        throw new Error(result?.message || `Failed to generate question paper. Status: ${response.status}`);
      }

      if (!result) {
        throw new Error("Backend returned an empty response.");
      }
      const expectedFilename = buildExpectedFilename({
        subject: form.subject,
        grade: form.grade,
        board: form.board,
        marks: form.totalMarks,
      });
      const resolvedFilename =
        result.docx_download_name && !looksAutoGeneratedFilename(result.docx_download_name)
          ? result.docx_download_name
          : result.docx_filename && !looksAutoGeneratedFilename(result.docx_filename)
            ? result.docx_filename
            : expectedFilename;
      const previewPaper = result.preview_paper || null;
      const resolvedPreviewPaper = previewPaper
        ? {
            ...previewPaper,
            title:
              previewPaper.title && previewPaper.title !== "Generated Question Paper"
                ? previewPaper.title
                : `${form.subject} - ${form.grade} Question Paper`,
            subject: previewPaper.subject || form.subject,
            grade: previewPaper.grade || form.grade,
            total_marks: previewPaper.total_marks || String(form.totalMarks),
          }
        : null;

      setBackendPrompt(result.prompt || null);
      setGeneratedDoc({
        id: `generated-${Date.now()}`,
        title: result.prompt?.title || `${form.subject} - ${form.grade} Question Paper`,
        previewText: result.preview_text || "No preview content returned from n8n.",
        previewPaper: resolvedPreviewPaper,
        docxUrl: result.docx_url ? new URL(result.docx_url, window.location.origin).toString() : "",
        downloadUrl: result.docx_download_url ? new URL(result.docx_download_url, window.location.origin).toString() : "",
        filename: resolvedFilename,
        sizeBytes: result.docx_size_bytes || 0,
        pageCount: result.docx_page_count || Math.max(1, Math.ceil((result.preview_text || "").length / 2400)),
        dateLabel: new Date().toLocaleDateString(),
        grade: form.grade,
        board: form.board,
        marks: form.totalMarks,
        subject: form.subject,
      });
      setVariantPreviews([]);
      setOutput(null);
      setStatus("preview");
    } catch (error) {
      console.error("Prompt generator request failed:", error);
      const errorMessage = error?.message || "Generation failed. Please check the backend or n8n response.";
      setGeneratedDoc(null);
      setGenerationError(errorMessage);
      showToast(errorMessage);
      setStatus("idle");
    }
  };

  const handleSelectVariant = (variant) => {
     setStatus("loading");
     setPreviewVariant(variant);
     timerRef.current = setTimeout(() => {
         setOutput(null);
         setStatus("variant_preview");
         const newExpanded = {};
         form.sections.forEach(s => newExpanded[s.id] = true);
         setExpandedSections(newExpanded);
     }, 800);
  };

  const handleGoBackToVariants = () => {
     setPreviewVariant(null);
     setOutput(null);
     setStatus("variants");
  };

  const handleConfirmVariant = () => {
     setShowConfirmDialog(true);
  };

  const finalizePaper = () => {
     setShowConfirmDialog(false);
     setStatus("generated");
  };

  const cancelConfirmation = () => {
     setShowConfirmDialog(false);
  };

  const handleSample = () => {
    setForm(defaultForm);
    setUploadedFiles([]);
    setFilesModalOpen(false);
    setFilePreview(null);
    setStatus("idle");
    setGenerationError("");
    setOutput(null);
    setBackendPrompt(null);
    setGeneratedDoc(null);
    setPreviewVariant(null);
    setShowConfirmDialog(false);
  };

  const toggleSection = (secId) => {
    setExpandedSections(prev => ({ ...prev, [secId]: !prev[secId] }));
  };

  const handleDownloadGeneratedDoc = async () => {
    const resolvedDownloadUrl = generatedDoc?.downloadUrl || generatedDoc?.docxUrl;
    if (!resolvedDownloadUrl) {
      return;
    }

    try {
      const response = await fetch(resolvedDownloadUrl);
      if (!response.ok) {
        throw new Error("Failed to download the generated file.");
      }

      const blob = await response.blob();
      const blobUrl = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobUrl;
      link.download = generatedDoc.filename || "generated-question-paper.docx";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(blobUrl);
    } catch (error) {
      showToast(error?.message || "Failed to download the generated file.");
    }
  };

  const panelStatus = status === "loading" ? "processing" : status === "generated" ? "completed" : "waiting";
  const panelFiles = generatedDoc
    ? [{
        id: generatedDoc.id || "generated-file",
        name: generatedDoc.filename || "generated-question-paper.docx",
        sizeBytes: generatedDoc.sizeBytes || 0,
        pageCount: generatedDoc.pageCount || 1,
        dateLabel: generatedDoc.dateLabel || new Date().toLocaleDateString(),
        downloadUrl: generatedDoc.downloadUrl || generatedDoc.docxUrl || "",
        previewText: generatedDoc.previewText || "",
      }]
    : [];

  return (
    <motion.div custom={-1} variants={pageVariants} initial="initial" animate="animate" exit="exit" className="relative z-10 flex h-screen flex-col overflow-hidden bg-[#fafcff]">
      
      {/* Blush tint background shine */}
      <div className="absolute inset-0 pointer-events-none z-0 overflow-hidden">
        <div className="absolute top-[-10%] left-[-5%] h-[60%] w-[50%] rounded-full bg-rose-200/20 blur-[130px]" />
        <div className="absolute bottom-[-10%] right-[-5%] h-[60%] w-[50%] rounded-full bg-pink-200/20 blur-[120px]" />
      </div>

      {/* Sidebar Overlay */}
      <AnimatePresence>
        {isSidebarOpen && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }} 
            onClick={() => setIsSidebarOpen(false)}
            className="fixed inset-0 z-40 bg-slate-900/20 backdrop-blur-sm" 
          />
        )}
        
        {/* Confirmation Dialog Overlay */}
        {showConfirmDialog && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-60 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4"
          >
             <motion.div 
                initial={{ scale: 0.9, opacity: 0 }} 
                animate={{ scale: 1, opacity: 1 }} 
                exit={{ scale: 0.9, opacity: 0 }}
                className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl border border-slate-100"
             >
                <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-blue-50 text-blue-500">
                   <Sparkles className="h-6 w-6"/>
                </div>
                <h3 className="text-center text-xl font-bold text-slate-800" style={{ fontFamily: '"Playfair Display", serif' }}>Are you sure?</h3>
                <p className="mt-2 text-center text-sm font-medium text-slate-500 leading-relaxed">
                   Confirming this paper will instantly finalize <strong className="text-slate-700">{previewVariant?.title}</strong> and discard the other 3 variants. Continue?
                </p>
                <div className="mt-6 flex gap-3">
                   <button onClick={cancelConfirmation} className="flex-1 rounded-xl bg-slate-100 px-4 py-3 text-sm font-semibold text-slate-600 transition-colors hover:bg-slate-200">
                      Cancel
                   </button>
                   <button onClick={finalizePaper} className="flex-1 flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white shadow-md transition-all hover:bg-blue-700">
                      Yes, Confirm
                   </button>
                </div>
             </motion.div>
          </motion.div>
        )}

        {/* Selection Modal */}
        {activeModal && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-60 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4"
            onClick={() => setActiveModal(null)}
          >
             <motion.div 
                initial={{ scale: 0.95, opacity: 0, y: 20 }} 
                animate={{ scale: 1, opacity: 1, y: 0 }} 
                exit={{ scale: 0.95, opacity: 0, y: 20 }}
                onClick={(e) => e.stopPropagation()}
                className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl border border-slate-100 flex flex-col max-h-[85vh]"
             >
                <div className="flex items-center justify-between mb-4">
                   <h3 className="text-xl font-bold text-slate-800" style={{ fontFamily: '"Playfair Display", serif' }}>
                     {activeModal === 'grade' ? 'Select Grade' : activeModal === 'board' ? 'Select Board' : 'Select Difficulty'}
                   </h3>
                   <button onClick={() => setActiveModal(null)} className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-slate-500 hover:bg-slate-200 transition-colors">
                      <X className="h-4 w-4" />
                   </button>
                </div>
                
                <div className="overflow-y-auto pr-2 space-y-2" style={{ scrollbarWidth: 'thin' }}>
                   {(activeModal === 'grade' ? GRADES : activeModal === 'board' ? BOARDS : DIFFICULTIES).map((item) => (
                      <button
                         key={item}
                         onClick={() => {
                            setForm({ ...form, [activeModal]: item });
                            setActiveModal(null);
                         }}
                         className={`w-full text-left px-4 py-3 rounded-xl text-sm font-medium transition-all ${form[activeModal] === item ? 'bg-blue-600 text-white shadow-md' : 'bg-slate-50 text-slate-700 hover:bg-blue-50 hover:text-blue-700 border border-slate-100'}`}
                      >
                         {item}
                      </button>
                   ))}
                </div>
             </motion.div>
          </motion.div>
        )}

        {/* Uploaded Files Modal */}
        {filesModalOpen && (
          <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-60 flex items-center justify-center bg-slate-900/40 backdrop-blur-sm p-4"
            onClick={() => setFilesModalOpen(false)}
          >
             <motion.div 
                initial={{ scale: 0.95, opacity: 0, y: 20 }} 
                animate={{ scale: 1, opacity: 1, y: 0 }} 
                exit={{ scale: 0.95, opacity: 0, y: 20 }}
                onClick={(e) => e.stopPropagation()}
                className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl border border-slate-100 flex flex-col max-h-[85vh]"
             >
                <div className="flex items-center justify-between mb-4">
                   <h3 className="text-xl font-bold text-slate-800" style={{ fontFamily: '"Playfair Display", serif' }}>
                     Uploaded files
                   </h3>
                   <button onClick={() => setFilesModalOpen(false)} className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-100 text-slate-500 hover:bg-slate-200 transition-colors">
                      <X className="h-4 w-4" />
                   </button>
                </div>
                
                <div className="flex-1 overflow-y-auto space-y-3 pr-2" style={{ scrollbarWidth: 'thin' }}>
                    <AnimatePresence>
                      {uploadedFiles.map((file, index) => (
                        <motion.div 
                          key={`${file.name}-${index}`}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          exit={{ opacity: 0, x: 20 }}
                          className="flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-3 hover:border-blue-300 transition-colors cursor-pointer"
                          onClick={() => handlePreviewFile(file)}
                        >
                            <div className="flex items-center gap-3 overflow-hidden">
                                <FileText className="h-5 w-5 text-blue-500 shrink-0" />
                                <span className="truncate text-sm font-medium text-slate-700">{file.name}</span>
                            </div>
                            <button 
                              onClick={(e) => {
                                e.stopPropagation();
                                setUploadedFiles(prev => {
                                  const updated = prev.filter((_, i) => i !== index);
                                  if (updated.length === 0) setFilesModalOpen(false);
                                  return updated;
                                });
                              }}
                              className="text-slate-400 hover:text-red-500 p-1 rounded transition-colors"
                            >
                                <X className="h-4 w-4" />
                            </button>
                        </motion.div>
                      ))}
                    </AnimatePresence>
                </div>
                
                <div className="mt-4 pt-4 border-t border-slate-100 flex justify-end">
                    <button onClick={() => {
                        setFilesModalOpen(false);
                        setTimeout(() => fileInputRef.current?.click(), 100);
                    }} className="flex items-center gap-2 rounded-xl bg-blue-50 text-blue-600 px-4 py-2 text-sm font-semibold transition-colors hover:bg-blue-100">
                        <Plus className="h-4 w-4" /> Add More Files
                    </button>
                </div>
             </motion.div>
          </motion.div>
        )}

        {/* File Preview Modal */}
        {filePreview && (
          <motion.div 
            initial={{ opacity: 0, y: 50 }} 
            animate={{ opacity: 1, y: 0 }} 
            exit={{ opacity: 0, y: 50 }}
            className="fixed inset-0 z-[70] flex flex-col bg-slate-900/90 backdrop-blur-md"
            onClick={closePreview}
          >
             <div className="flex items-center justify-between p-4 text-white border-b border-white/10 shrink-0">
                <h3 className="font-semibold text-lg truncate pr-4">{filePreview.name}</h3>
                <button onClick={closePreview} className="p-2 rounded-full hover:bg-white/10 transition-colors">
                   <X className="h-6 w-6" />
                </button>
             </div>
             <div className="flex-1 overflow-hidden flex items-center justify-center p-4">
                 <div onClick={(e) => e.stopPropagation()} className="w-full h-full max-w-6xl max-h-full flex items-center justify-center">
                     {filePreview.type === 'image' ? (
                         <img src={filePreview.url} alt={filePreview.name} className="max-w-full max-h-full object-contain rounded-lg shadow-2xl" />
                     ) : filePreview.type === 'pdf' ? (
                         <iframe src={filePreview.url} className="w-full h-full rounded-lg bg-white shadow-2xl" title={filePreview.name} />
                     ) : (
                         <div className="text-center text-white/70 bg-white/5 p-8 rounded-2xl border border-white/10 shadow-2xl max-w-sm">
                            <FileText className="h-16 w-16 mx-auto mb-4 text-white/30" />
                            <p className="font-semibold text-lg mb-2">Preview not available</p>
                            <p className="text-sm">Cannot preview {filePreview.name}. Click outside to close.</p>
                         </div>
                     )}
                 </div>
             </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Sidebar Panel */}
      <div className={`fixed top-0 left-0 z-50 flex h-full w-[260px] flex-col bg-slate-50 shadow-[4px_0_24px_rgba(0,0,0,0.05)] transition-transform duration-300 ease-in-out ${isSidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
         <div className="flex shrink-0 items-center justify-between p-3 border-b border-slate-200/60">
             <button onClick={() => { setIsSidebarOpen(false); handleSample(); }} className="flex w-full items-center gap-2 rounded-lg bg-white border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 shadow-sm transition-all hover:bg-slate-100 hover:shadow">
               <Plus className="h-4 w-4" /> New Paper
             </button>
             <button onClick={() => setIsSidebarOpen(false)} className="ml-2 flex shrink-0 h-9 w-9 items-center justify-center rounded-lg text-slate-500 hover:bg-slate-200 hover:text-slate-800 transition-colors focus:outline-none">
               <X className="h-5 w-5" />
             </button>
         </div>
         <div className="flex-1 overflow-y-auto px-3 py-4 space-y-6">
            <div>
              <p className="px-2 text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-2">Today</p>
              
              {/* Nested Session Doc Structure */}
              <div className="rounded-xl bg-white border border-blue-200/50 shadow-sm overflow-hidden border-l-2 border-l-blue-500">
                <button className="w-full flex items-center gap-3 px-3 py-2.5 text-[13px] font-medium text-blue-700 bg-blue-50/50 transition-colors">
                   <MessageSquare className="h-4 w-4 shrink-0 text-blue-500" />
                   <span className="truncate">Grade 11 Physics Midterm</span>
                </button>
                <div className="bg-slate-50/50 border-t border-slate-100 py-1.5 space-y-0.5">
                   <button className="w-full flex items-center justify-between text-left px-3 py-1.5 text-[11px] font-medium text-slate-600 hover:bg-white hover:text-blue-600 transition-colors group">
                     <span className="flex items-center gap-2 truncate pl-7">
                        <FileText className="h-3 w-3 shrink-0 text-slate-400 group-hover:text-blue-500" />
                        Physics_Analytical_Variant.pdf
                     </span>
                   </button>
                   <button className="w-full flex items-center justify-between text-left px-3 py-1.5 text-[11px] font-medium text-slate-600 hover:bg-white hover:text-blue-600 transition-colors group">
                     <span className="flex items-center gap-2 truncate pl-7">
                        <FileText className="h-3 w-3 shrink-0 text-slate-400 group-hover:text-blue-500" />
                        Physics_Objective_Variant.pdf
                     </span>
                   </button>
                </div>
              </div>
            </div>
            
            <div>
              <p className="px-2 text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-2">Yesterday</p>
              <div className="rounded-xl bg-white border border-slate-200/50 shadow-sm overflow-hidden">
                <button className="w-full flex items-center gap-3 px-3 py-2.5 text-[13px] font-medium text-slate-600 hover:bg-slate-50 transition-colors">
                   <MessageSquare className="h-4 w-4 shrink-0 text-slate-400" />
                   <span className="truncate">Conceptual Biology Quiz</span>
                </button>
                <div className="bg-slate-50/50 border-t border-slate-100 py-1.5 space-y-0.5">
                   <button className="w-full flex items-center justify-between text-left px-3 py-1.5 text-[11px] font-medium text-slate-600 hover:bg-white hover:text-blue-600 transition-colors group">
                     <span className="flex items-center gap-2 truncate pl-7">
                        <FileText className="h-3 w-3 shrink-0 text-slate-400" />
                        Bio_Theoretical_Variant.pdf
                     </span>
                   </button>
                </div>
              </div>
            </div>

            <div>
              <p className="px-2 text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-2">Previous 7 Days</p>
              <button className="w-full flex items-center gap-3 rounded-lg px-2.5 py-2 text-[13px] font-medium text-slate-600 hover:bg-slate-200/70 transition-colors">
                 <MessageSquare className="h-4 w-4 shrink-0 text-slate-400" />
                 <span className="truncate">Advanced Mathematics</span>
              </button>
            </div>
         </div>
      </div>

      {/* Header */}
      <header className="flex h-16 shrink-0 items-center justify-between border-b border-blue-100 bg-white/80 px-4 sm:px-8 backdrop-blur-md">
        <div className="flex items-center gap-2 sm:gap-3">
          <button onClick={() => setIsSidebarOpen(true)} className="flex h-9 w-9 items-center justify-center rounded-xl text-slate-500 transition-colors hover:bg-slate-100 hover:text-slate-800 focus:outline-none focus:ring-2 focus:ring-blue-100">
             <Menu className="h-5 w-5" />
          </button>
          <div className="ml-1 flex h-9 w-9 items-center justify-center overflow-hidden rounded-xl bg-blue-50 shadow-sm border border-blue-100/50">
            <img src="/appLogo.png" alt="App Logo" className="h-[120%] w-[120%] object-cover" />
          </div>
          <span className="text-xl font-bold tracking-tight text-slate-800" style={{ fontFamily: '"Playfair Display", serif' }}>
            Question Paper Generator
          </span>
        </div>
        <div className="flex items-center gap-6">
           <button onClick={onAbout} className="text-[12px] font-bold tracking-widest text-slate-400 hover:text-blue-600 transition-colors uppercase">
              About
           </button>
           <button onClick={onBack} className="text-[12px] font-bold tracking-widest text-slate-400 hover:text-blue-600 transition-colors uppercase">
              Home Page
           </button>
        </div>
      </header>

      {/* BODY GRID */}
      <main className="grid min-h-0 flex-1 grid-cols-1 gap-6 p-6 lg:grid-cols-[minmax(350px,40%)_minmax(0,60%)]">
        
        {/* LEFT PANEL - Simple Inputs */}
        <section className="flex flex-col overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm">
          <div className="flex-1 overflow-y-auto no-scrollbar bg-[#fafafc] p-6 sm:p-8">
            <div className="space-y-6">
              
              {/* Optional Upload Source */}
              <div 
                 onDragOver={handleDragOver} 
                 onDrop={handleDrop}
                 onClick={() => {
                   if (uploadedFiles.length > 0) {
                     setFilesModalOpen(true);
                   } else {
                     fileInputRef.current?.click();
                   }
                 }}
                 className="group flex h-20 cursor-pointer items-center justify-between rounded-xl border-2 border-dashed border-blue-200 bg-slate-50/50 px-5 transition-all hover:bg-blue-50/50 hover:border-blue-400"
               >
                 <input type="file" ref={fileInputRef} className="hidden" multiple accept=".docx,.pdf,.png,.jpg,.jpeg,.bmp,.tif,.tiff,.webp" onChange={(e) => {
                   if (e.target.files && e.target.files.length > 0) {
                     const newFiles = Array.from(e.target.files).filter(f => {
                       if (f.size > MAX_UPLOAD_SIZE_BYTES) {
                         showToast(`File ${f.name} exceeds 100MB.`);
                         return false;
                       }
                       return true;
                     });
                     if (newFiles.length > 0) {
                       setUploadedFiles(prev => [...prev, ...newFiles]);
                     }
                     e.target.value = "";
                   }
                 }} />
                 <div className="flex items-center gap-4">
                    <div className="flex h-10 w-10 items-center justify-center rounded-[10px] bg-white border border-blue-100 shadow-sm text-slate-400 transition-colors group-hover:text-blue-500">
                       <UploadCloud className="h-5 w-5" />
                    </div>
                    <div>
                       <p className="text-sm font-semibold text-slate-700">
                         {uploadedFiles.length > 0 ? `${uploadedFiles.length} file(s) uploaded` : "Upload Source Material"}
                       </p>
                       <p className="text-[11px] font-medium text-slate-400">
                         {uploadedFiles.length > 0 ? "Click to view or add more files" : "Optional: drop .docx, .pdf, or image files here for OCR context (max 100 MB)"}
                       </p>
                    </div>
                 </div>
              </div>

              {/* Form Grid */}
              <div className="grid grid-cols-[1fr_100px] gap-4">
                <div>
                  <label className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Subject</label>
                  <input type="text" value={form.subject} onChange={(e) => setForm({...form, subject: e.target.value})} className="w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-medium text-slate-800 transition-colors placeholder:text-slate-300 focus:border-blue-400 focus:outline-none focus:ring-4 focus:ring-blue-50" placeholder="e.g. Physics" />
                </div>
                <div>
                  <label className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Marks</label>
                  <input type="number" min="10" max="100" value={form.totalMarks} onChange={(e) => setForm({...form, totalMarks: Number(e.target.value)})} className="w-full rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-medium text-slate-800 transition-colors focus:border-blue-400 focus:outline-none focus:ring-4 focus:ring-blue-50 text-center" />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pb-5 border-b border-slate-100">
                <div>
                  <label className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Grade</label>
                  <button
                    type="button"
                    onClick={() => setActiveModal('grade')}
                    className={`flex w-full items-center justify-between rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-medium transition-colors hover:border-blue-400 focus:border-blue-400 focus:outline-none focus:ring-4 focus:ring-blue-50 ${!form.grade ? "text-slate-400" : "text-slate-800"}`}
                  >
                    <span className="truncate">{form.grade || "Enter Grade"}</span>
                    <ChevronDown className="h-4 w-4 text-slate-400 shrink-0" />
                  </button>
                </div>
                <div>
                  <label className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Board</label>
                  <button
                    type="button"
                    onClick={() => setActiveModal('board')}
                    className={`flex w-full items-center justify-between rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-medium transition-colors hover:border-blue-400 focus:border-blue-400 focus:outline-none focus:ring-4 focus:ring-blue-50 ${!form.board ? "text-slate-400" : "text-slate-800"}`}
                  >
                    <span className="truncate">{form.board || "Select Board"}</span>
                    <ChevronDown className="h-4 w-4 text-slate-400 shrink-0" />
                  </button>
                </div>
                <div>
                  <label className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Difficulty</label>
                  <button
                    type="button"
                    onClick={() => setActiveModal('difficulty')}
                    className={`flex w-full items-center justify-between rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-medium transition-colors hover:border-blue-400 focus:border-blue-400 focus:outline-none focus:ring-4 focus:ring-blue-50 ${!form.difficulty ? "text-slate-400" : "text-slate-800"}`}
                  >
                    <span className="truncate">{form.difficulty || "Select Difficulty"}</span>
                    <ChevronDown className="h-4 w-4 text-slate-400 shrink-0" />
                  </button>
                </div>
              </div>

              {/* Prompt Box */}
              <div>
                <label className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-500">Custom Prompt</label>
                <textarea 
                  ref={promptTextareaRef}
                  rows={2}
                  value={form.prompt}
                  onChange={(e) => setForm({...form, prompt: e.target.value})}
                  placeholder="E.g., Emphasize critical thinking..."
                  className="w-full resize-none overflow-hidden rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 text-sm font-medium text-slate-800 transition-colors placeholder:text-slate-300 focus:border-blue-400 focus:outline-none focus:ring-4 focus:ring-blue-50"
                />
              </div>

            </div>
          </div>
          
          {/* Action Area */}
          <div className="shrink-0 space-y-3 bg-white p-6 sm:p-8 border-t border-slate-100">
            <button 
              onClick={handleGenerate}
              disabled={status === 'loading'}
              className="relative overflow-hidden group flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3.5 text-sm font-semibold text-white shadow-md transition-all hover:bg-blue-700 active:scale-[0.98] disabled:pointer-events-none focus:outline-none focus:ring-4 focus:ring-blue-100"
            >
              {status === 'loading' ? (
                <>
                  <div className="relative flex items-center justify-center h-5 w-5 mr-1">
                    <motion.div 
                      animate={{ x: [-1, 1.5, -1, 1, 0], y: [-1, 1, -1.5, 1, 0] }}
                      transition={{ duration: 0.15, repeat: Infinity }}
                      className="absolute z-10"
                    >
                      <Zap className="h-5 w-5 fill-yellow-400 text-yellow-300 drop-shadow-[0_0_8px_rgba(250,204,21,0.8)]" />
                    </motion.div>
                    <motion.div
                      animate={{ y: [0, -40], opacity: [0.8, 0], scale: [1, 0.8] }}
                      transition={{ duration: 0.25, repeat: Infinity, ease: "easeIn" }}
                      className="absolute z-0"
                    >
                      <Zap className="h-5 w-5 fill-yellow-400 text-yellow-500 blur-[2px]" />
                    </motion.div>
                    <motion.div
                      animate={{ y: [0, -50], opacity: [0.5, 0], scale: [1, 0.5] }}
                      transition={{ duration: 0.2, repeat: Infinity, ease: "easeIn", delay: 0.1 }}
                      className="absolute z-0"
                    >
                      <Zap className="h-5 w-5 fill-yellow-300 text-yellow-400 blur-[3px]" />
                    </motion.div>
                  </div>
                  <motion.span animate={{ opacity: [1, 0.7, 1] }} transition={{ duration: 0.8, repeat: Infinity }}>
                    Generating...
                  </motion.span>
                </>
              ) : (
                <>
                  <Zap className="h-4 w-4 text-white" />
                  Generate Paper
                </>
              )}
            </button>
            <button 
              onClick={handleSample}
              disabled={status === 'loading'}
              className="flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-600 shadow-sm transition-all hover:bg-slate-50 hover:text-slate-900 focus:outline-none active:scale-[0.98] disabled:pointer-events-none"
            >
              <FileText className="h-4 w-4 text-slate-400" />
              Reset
            </button>
          </div>
        </section>

        {/* RIGHT PANEL - Clean UI Output */}
        <section className="flex flex-col overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm relative">
          <div className="flex h-16 shrink-0 items-center justify-between border-b border-slate-100 bg-white px-8">
            <div className="flex items-center gap-3">
              {status === 'idle' && <span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-slate-500">Waiting</span>}
              {status === 'loading' && <span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-blue-600 animate-pulse">Processing...</span>}
              {status === 'variants' && <span className="rounded-full bg-purple-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-purple-600 animate-pulse">Action Required</span>}
              {status === 'variant_preview' && <span className="flex items-center gap-1.5 rounded-full bg-amber-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-amber-700"><CheckCircle2 className="h-3.5 w-3.5" /> Previewing Mode</span>}
              {status === 'generated' && <span className="flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5" /> Finalized</span>}
              {status === 'preview' && <span className="flex items-center gap-1.5 rounded-full bg-amber-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-amber-700"><CheckCircle2 className="h-3.5 w-3.5" /> Preview Ready</span>}
            </div>
            {status === 'generated' && generatedDoc?.docxUrl && (
              <div className="flex items-center gap-5">
                <a href={generatedDoc.downloadUrl || generatedDoc.docxUrl} download={generatedDoc.filename} className="flex items-center gap-2 text-[12px] font-semibold text-slate-500 hover:text-blue-600 transition-colors">
                  <Printer className="h-4 w-4" /> Download .docx
                </a>
              </div>
            )}
            {status === 'variant_preview' && (
              <div className="flex items-center gap-4">
                 <button onClick={handleGoBackToVariants} className="text-[12px] font-bold text-slate-400 hover:text-slate-600 transition-colors">
                    ← Go Back
                 </button>
                 <button onClick={handleConfirmVariant} className="rounded-lg bg-blue-600 px-4 py-2 text-[12px] font-bold text-white shadow-sm hover:bg-blue-700 transition-colors">
                    Confirm this Paper
                 </button>
              </div>
            )}
          </div>
          
          <div className="flex-1 overflow-y-auto bg-[#fafafc] p-6 sm:p-8">
            {(status === 'idle' || status === 'loading' || status === 'generated') && (
              <div className="space-y-4">
                {generationError && status !== 'loading' && (
                  <div className={`mx-auto max-w-xl rounded-2xl border px-5 py-4 text-left shadow-sm ${generationError.includes("Internal server error") ? 'border-amber-200 bg-amber-50' : 'border-rose-200 bg-rose-50'}`}>
                    <p className={`text-[11px] font-bold uppercase tracking-[0.22em] ${generationError.includes("Internal server error") ? 'text-amber-700' : 'text-rose-700'}`}>
                      {generationError.includes("Internal server error") ? 'System Error' : 'Generation blocked'}
                    </p>
                    <p className={`mt-2 text-sm font-medium leading-6 ${generationError.includes("Internal server error") ? 'text-amber-900' : 'text-rose-900'}`}>{generationError}</p>
                  </div>
                )}
                <DocumentGenerationPanel
                  status={panelStatus}
                  files={panelFiles}
                />
              </div>
            )}

            {status === 'preview' && generatedDoc && (
              <div className="mx-auto max-w-4xl animate-fade-up space-y-6">
                <div className="rounded-3xl border border-blue-100 bg-white p-6 shadow-sm">
                  <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                      <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-blue-600">Preview</p>
                      <h2 className="mt-2 text-2xl font-bold text-slate-900" style={{ fontFamily: '"Playfair Display", serif' }}>
                        {generatedDoc.title}
                      </h2>
                      <p className="mt-2 text-sm text-slate-500">
                        {generatedDoc.subject || form.subject} {generatedDoc.grade ? `| ${generatedDoc.grade}` : ""} {generatedDoc.board ? `| ${generatedDoc.board}` : ""} {generatedDoc.marks ? `| ${generatedDoc.marks} Marks` : ""}
                      </p>
                      <p className="mt-3 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400">
                        Download name: {generatedDoc.filename}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-3">
                      <button
                        type="button"
                        onClick={handleGenerate}
                        className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 shadow-sm transition-all hover:bg-slate-50"
                      >
                        <RotateCcw className="h-4 w-4" />
                        Generate Again
                      </button>
                      <button
                        type="button"
                        onClick={handleDownloadGeneratedDoc}
                        className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white shadow-md transition-all hover:bg-blue-700"
                      >
                        <Download className="h-4 w-4" />
                        Download .docx
                      </button>
                    </div>
                  </div>
                </div>

                <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                  <div className="mb-4 flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-50 text-blue-600">
                      <FileText className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-bold text-slate-900">Question Paper Preview</h3>
                      <p className="text-sm text-slate-500">Review the generated content before downloading.</p>
                    </div>
                  </div>
                  <div className="max-h-[34rem] overflow-y-auto rounded-2xl bg-[#f8f6f2] p-6 sm:p-8">
                    <div className="mx-auto max-w-3xl rounded-[28px] border border-slate-200 bg-white px-6 py-8 shadow-[0_18px_40px_rgba(15,23,42,0.08)] sm:px-10">
                      <div className="space-y-6">
                        <PreviewPaper paper={generatedDoc.previewPaper} previewText={generatedDoc.previewText} />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {status === 'variants' && (
              <div className="mx-auto max-w-4xl animate-fade-up">
                 <div className="mb-8 text-center mt-4">
                    <div className="inline-flex items-center justify-center h-16 w-16 rounded-full bg-blue-50 text-blue-500 mb-6 shadow-sm border border-blue-100">
                       <Sparkles className="h-8 w-8" />
                    </div>
                    <h2 className="text-3xl font-bold text-slate-800" style={{ fontFamily: '"Playfair Display", serif' }}>Select Paper Variant</h2>
                    <p className="text-base text-slate-500 mt-3 max-w-sm mx-auto">We generated 4 distinct styles for your prompt. Select one to finalize your document.</p>
                 </div>

                 <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                     {variantPreviews.map(v => {
                        const Icon = v.iconType;
                        return (
                         <button key={v.id} onClick={() => handleSelectVariant(v)} className="group relative flex flex-col text-left p-6 rounded-2xl border-2 border-slate-200/60 bg-white shadow-sm hover:border-blue-400 hover:bg-blue-50/50 transition-all focus:outline-none hover:-translate-y-1">
                            <div className="flex w-full items-start justify-between mb-5">
                               <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-slate-100 text-slate-500 transition-colors group-hover:bg-blue-600 group-hover:text-white shadow-sm">
                                  <Icon className="h-6 w-6" />
                               </div>
                               <span className="text-[10px] font-bold uppercase tracking-widest text-slate-400 group-hover:text-blue-500">Preview</span>
                            </div>
                            <h3 className="text-lg font-bold text-slate-800 mb-2">{v.title}</h3>
                            <p className="text-sm font-medium text-slate-500 leading-relaxed pr-4">{v.description}</p>
                            
                            <div className="absolute inset-0 border-2 border-blue-400 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none shadow-[0_10px_30px_-10px_rgba(37,99,235,0.3)]"></div>
                         </button>
                        )
                     })}
                  </div>

                 {backendPrompt?.source_document?.chunks?.length > 0 && (
                   <div className="mt-6 rounded-2xl border border-blue-100 bg-white p-6 shadow-sm">
                     <div className="flex items-center justify-between gap-4">
                       <div>
                         <h3 className="text-lg font-bold text-slate-800">Extracted Source Chunks</h3>
                         <p className="mt-1 text-sm text-slate-500">
                           {backendPrompt.source_document.file_type?.toUpperCase() || "DOCUMENT"} content extracted on the backend and stored as an array.
                         </p>
                       </div>
                       <span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-blue-700">
                         {backendPrompt.source_document.chunks.length} chunks
                       </span>
                     </div>

                     <div className="mt-4 space-y-3">
                       {backendPrompt.source_document.chunks.slice(0, 3).map((chunk, index) => (
                         <div key={index} className="rounded-xl border border-slate-200 bg-slate-50 p-4">
                           <p className="mb-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">Chunk {index + 1}</p>
                           <p className="text-sm leading-6 text-slate-700 whitespace-pre-wrap">{chunk}</p>
                         </div>
                       ))}
                     </div>
                   </div>
                 )}
              </div>
            )}

            {(status === 'generated' || status === 'variant_preview') && output && (
              <div className="mx-auto max-w-3xl space-y-6 animate-fade-up">
                <div className="rounded-xl border border-blue-100 bg-white p-8 text-center shadow-sm relative overflow-hidden">
                  <div className="absolute top-0 left-0 w-full h-1 bg-blue-500" />
                  <h2 className="text-3xl font-bold text-slate-900 mb-3" style={{ fontFamily: '"Playfair Display", serif' }}>
                    {output.examInfo.subject}
                  </h2>
                  <p className="text-sm font-semibold uppercase tracking-widest text-slate-500 mb-5">
                    {output.examInfo.board} • {output.examInfo.grade}
                  </p>
                  
                  <div className="inline-block mt-1 mb-5">
                     <span className="px-3 py-1.5 rounded-full bg-purple-50 text-[10px] font-bold uppercase tracking-widest text-purple-700 border border-purple-100">
                       {output.examInfo.variantTitle}
                     </span>
                  </div>

                  <div className="flex flex-wrap items-center justify-center gap-x-6 gap-y-2 border-t border-slate-100 pt-5 text-sm font-medium text-slate-600">
                    <div className="flex gap-2">
                       <span className="text-slate-400">Marks:</span>
                       <span className="text-slate-900 font-bold">{output.examInfo.totalMarks}</span>
                    </div>
                    <div className="hidden h-1.5 w-1.5 rounded-full bg-slate-200 sm:block" />
                    <div className="flex gap-2">
                       <span className="text-slate-400">Time:</span>
                       <span className="text-slate-900 font-bold">{output.examInfo.duration}</span>
                    </div>
                  </div>
                </div>
                
                {output.sections.map((sec) => (
                  <div key={sec.section} className="overflow-hidden rounded-xl bg-white border border-blue-100 shadow-sm transition-all pb-2">
                    <button 
                      onClick={() => toggleSection(sec.section)}
                      className="group flex w-full items-center justify-between bg-white px-5 py-4 transition-colors hover:bg-slate-50 focus:outline-none"
                    >
                      <div className="flex items-center gap-4 text-left">
                        <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-[16px] font-bold text-blue-600 transition-colors group-hover:bg-blue-100" style={{ fontFamily: '"Playfair Display", serif' }}>
                          {sec.section}
                        </span>
                        <div>
                          <p className="font-bold text-slate-800 break-words line-clamp-2 pr-2">{sec.type}</p>
                          <p className="flex items-center gap-1.5 text-xs font-semibold text-slate-400 mt-0.5">
                             <Zap className="h-3 w-3 text-yellow-400" /> {sec.marksPerQuestion} Marks Per Q
                          </p>
                        </div>
                      </div>
                      {expandedSections[sec.section] ? <ChevronDown className="h-5 w-5 shrink-0 text-slate-400 transition-transform" /> : <ChevronRight className="h-5 w-5 shrink-0 text-slate-400 transition-transform" />}
                    </button>
                    
                    {expandedSections[sec.section] && (
                      <div className="space-y-4 px-5 pt-2 pb-4">
                        {sec.questions.map((q, idx) => (
                          <div key={idx} className="flex gap-4 border-t border-slate-50 pt-4 first:border-0 first:pt-0">
                            <span className="text-sm font-bold text-blue-500 mt-0.5 whitespace-nowrap">Q{idx + 1}.</span>
                            <div className="flex-1">
                              {typeof q === 'string' ? (
                                <p className="text-[14px] leading-relaxed text-slate-700">{q}</p>
                              ) : (
                                <div>
                                  <p className="text-[14px] leading-relaxed text-slate-700 mb-3">{q.text}</p>
                                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                                    {q.options.map((opt, oIdx) => (
                                      <div key={oIdx} className="flex items-center gap-3 rounded-lg border border-slate-200 bg-white px-3.5 py-2.5 transition-colors hover:border-blue-300 hover:bg-blue-50">
                                        <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-slate-100 text-[11px] font-bold text-slate-500">
                                          {String.fromCharCode(65 + oIdx)}
                                        </span>
                                        <span className="text-[13px] font-medium text-slate-700">{opt}</span>
                                      </div>
                                    ))}
                                  </div>
                                </div>
                              )}
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </section>
      </main>
    </motion.div>
  );
}
